components:
  schemas:
    AttackGraph:
      required:
        - id
      properties:
        HasDevices:
          description: "The list of AG devices belonging to the graph."
          type: array
          x-ngsi:
            type: "Relationship"
      type: object
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/Ale96Pa/data-model-security/main/AttackGraph/type-definitions.json"
    AGDevice:
      required: -id
      properties:
        class:
          description: "The class of the AG device among"
          type: string
          x-ngsi:
            type: "Property"
        hostname:
          description: "Name of the AG device"
          type: string
          x-ngsi:
            type: "Property"
        InAttackGraph:
          description: "List of attack graphs in which the AG device belongs to"
          type: array
          x-ngsi:
            type: "Relationship"
        IsConnectedTo:
          description: "List of AG devices to which the current device is connected"
          type: array
          x-ngsi:
            type: "Relationship"
        HasVulnerabilities:
          description: "List of vulnerabilities in the AG device"
          type: array
          x-ngsi:
            type: "Relationship"
        IsTargetOf:
          description: "List of attack paths targeting the AG device"
          type: array
          x-ngsi:
            type: "Relationship"
      type: object
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/Ale96Pa/data-model-security/main/AttackGraph/type-definitions.json"
    AttackPath:
      required: -id
      properties:
        impact:
          description: "Attack Path Impact"
          type: number
          x-ngsi:
            type: "Property"
        likelihood:
          description: "Attack Path Likelihood"
          type: number
          x-ngsi:
            type: "Property"
        risk:
          description: "Attack Path Risk"
          type: number
          x-ngsi:
            type: "Property"
        path:
          description: "Attack Path trace"
          type: string
          x-ngsi:
            type: "Property"
      type: object
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/Ale96Pa/data-model-security/main/AttackGraph/type-definitions.json"

    Vulnerability:
      allOf:
        - $ref: "https://csrc.nist.gov/schema/nvd/api/2.0/cve_api_json_2.0.schema"
      properties:
        HasMitigations:
          description: "List of mitigation actions for the vulnerability"
          type: array
          x-ngsi:
            type: "Relationship"
      type: object
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/Ale96Pa/data-model-security/main/AttackGraph/type-definitions.json"
    Mitigation:
      required:
        - id
      properties:
        phase:
          description: "Devlopment phase in which the mitigation can be applied"
          type: string
          x-ngsi:
            type: "Property"
        strategy:
          description: "Strategy to put in place the mitigation"
          type: string
          x-ngsi:
            type: "Property"
        weakness:
          description: "CWE ID corresponding to the mitiigation"
          type: string
          x-ngsi:
            type: "Property"
        action:
          description: "Natural Language description of the mitigation"
          type: string
          x-ngsi:
            type: "Property"
      type: object
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/Ale96Pa/data-model-security/main/AttackGraph/type-definitions.json"

info:
  description: "Data Models used for AttackGraph"
  title: AttackGraphModeling
  version: "1.0.0"
openapi: "3.0.3"
paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        "200":
          content:
            application/ld+json:
              schema:
                type: object
          description: OK
