components:
  schemas:
    SecurityTrust:
      required:
        - id
      properties:
        host_id:
          description: "The device id of the advertisement publisher."
          type: string
          x-ngsi:
            type: "Property"
        vuln_id:
          description: "The vulnerability id of the security advertisement."
          type: string
          x-ngsi:
            type: "Property"
        updated:
          description: "Percentage of updated softwares on the total vulnerable ones."
          type: number
          x-ngsi:
            type: "Property"
        resources:
          description: "Resource limits of the publisher."
          type: number
          x-ngsi:
            type: "Property"
        internal_checks:
          description: "Percentage of passed security checks on the total ones."
          type: number
          x-ngsi:
            type: "Property"
      type: object
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/Ale96Pa/data-model-security/main/SecurityTrust/type-definitions.json"

info:
  description: "Data Models used for AttackGraph"
  title: AttackGraphModeling
  version: "1.0.0"
openapi: "3.0.3"
paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        "200":
          content:
            application/ld+json:
              schema:
                type: object
          description: OK
